#!/usr/bin/env python3
# Bake an ATLAS .json export into a range module.
# Usage: python scripts/bake-range.py <export.json> "<Range name>" [corrections.json] > ranges/<slug>.js
# Corrections: {"names": {hex: name}, "swap": [[hex, hex]], "drop_factions": [faction]}
import json, sys

src = json.load(open(sys.argv[1], encoding="utf-8"))
name = sys.argv[2] if len(sys.argv) > 2 else None
fixes = json.load(open(sys.argv[3], encoding="utf-8")) if len(sys.argv) > 3 else {}

cfg = dict(src.get("config", {}))
if name:
    cfg["name"] = name

hexes = {hid: v for hid, v in src.get("hexes", {}).items()
         if any(v.get(k) for k in ("terrain", "weather", "feature", "sign",
                                   "encounter", "discovery", "sites",
                                   "settlements", "notes", "name"))}

for a, b in fixes.get("swap", []):
    if a in hexes and b in hexes:
        ha, hb = hexes[a], hexes[b]
        ha["id"], hb["id"] = hb["id"], ha["id"]
        hexes[a], hexes[b] = hb, ha

# A hex's name also names its lone site or settlement, if unnamed or still on the old name.
for hid, label in fixes.get("names", {}).items():
    h = hexes.get(hid)
    if not h:
        continue
    was = h.get("name") or ""
    h["name"] = label
    blocks = h.get("settlements") or h.get("sites") or []
    if len(blocks) == 1 and blocks[0].get("name", "") in ("", was):
        blocks[0]["name"] = label

for gone in fixes.get("drop_factions", []):
    for h in hexes.values():
        if gone in h.get("factions", []):
            h["factions"] = [f for f in h["factions"] if f != gone]

seed = {"version": src.get("version", 1), "config": cfg, "hexes": hexes}
out = ("// %s — generated by scripts/bake-range.py\n\n" % cfg.get("name", "Range")
       + "export const RANGE = " + json.dumps(seed, ensure_ascii=False, separators=(",", ":")) + ";\n")
sys.stdout.buffer.write(out.encode("utf-8"))
